### PR TITLE
Login page UI-Changes

### PR DESCRIPTION
**Pull request by shiv-2810**
Changing the ui of login form and introducing animation from react-na…

### CODE REVIEW

**Review by silenteyesoncode — CHANGES_REQUESTED** [review]
Screenshot 2023-05-07 195220

**Comment by shiv-2810** [comment]
use -> expo start -c

u have to kill the running terminal and then run

**Comment by shiv-2810** [comment]
Does my code is running?

**Comment by silenteyesoncode** [comment]
Yes

**Comment by shiv-2810** [comment]
Then why u didn't merge?

**Comment by silenteyesoncode** [comment]
You PR will be merge of course. Cos i'm traveling @palindrome-kasak and @nandini25-ag will assist you here

Thanks

**Comment by nandini25-ag** [comment]
for better contribution ,I suggest you to make the same changes for sign up screen that would be better for the UI of the application. let me know for further process
Thanks.

**Pull request closed without merging**
